### ISSUE TITLE
#001 - Logic to handle child processes (workers) being killed by the OS (for example, due to Out Of Memory (OOM))

### ISSUE THREAD

**Issue by artpdr** [bioslikk/condu#1]
I'm creating an issue for this change in condu because it might change a vast proportion of code.
The problem is:
- When a worker process (child process that polls tasks from conductor server) is killed by the OS, for example due to OOM, there is no way to update the task being treated by the process that is gone as "FAILED".
- The process that is killed is set as a Zombie process and the task type that was being handled by this process is never polled again from this worker.

The solution that I will provide is:
- When child processes are triggered, they will be triggered from different threads that maintain a pipe open to the process that is triggered. 
- Whenever the process receives a task from Conductor server it communicates this task with the thread that triggered the process.
- If the child process is killed, for example due to OOM, the thread that created the process can observe this and can update the task as FAILED and create a new process to replace the one killed before.

For any doubts or suggestions, comment please.

**Comment by artpdr** [comment]
It seems that I will need to trigger new processes instead of new threads as launching processes from multi-thread processes seems problematic

**Comment by bioslikk** [comment]
Yup, that's what I meant to say. Multiprocessing lib is awesome to tackle that problem.

**Comment by artpdr** [comment]
Finished this using just processes. There is no multi-threading....
